linters:
  disable-all: true
  enable:
    - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    # exportloopref removed - Go 1.22+ has proper loop variable semantics
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  # Removed "Using the variable on range scope" exclude - fixed in Go 1.22+

linters-settings:
  errcheck:
    exclude: .errcheck-exclude
