linters:
  disable-all: true
  enable:
    - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  exclude:
    - Using the variable on range scope .* in function literal
  # depguard:
  #   rules:
  #     Main:
  #       files:
  #         - "$all"
  #       # List of allowed packages.
  #       allow:
  #         - $gostd
  #         - github.com/OpenPeeDeeP
  #         - github.com/Masterminds/semver
  #         - github.com/aws
  #         - github.com/jedib0t
  #         - github.com/mateimicu
  #         - github.com/spf13
  #         - github.com/stretchr - k8s.io
  #       # Packages that are not allowed where the value is a suggestion.
  #       deny:


linters-settings:
  errcheck:
    exclude: .errcheck-exclude
  gomnd:
    settings:
      mnd:
        # TODO(mmicu): exclude this when golangci-lint will include v2.0.0 of go-mnd
        excludes: argument
