project_name: kdiscover

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: general
    goos:
      - windows
      - linux
      - freebsd

  - id: macos
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

source:
  enabled: true

release:
  prerelease: auto

changelog:
  skip: false

brews:
  - repository:
      owner: mateimicu
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@mateimicu.com
    folder: Formula
    description: "Utility for listing and exporting config for K8s Clusters"
    test: |
      system "#{bin}/kdiscover --version"
    install: |
      bin.install "kdiscover"
