apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: discover
spec:
  version: {{ .TagName }}
  homepage: https://github.com/mateimicu/kdiscover
  shortDescription: "Discover Kubernetes clusters and export configs"
  description: |
    Discover all the cluster from a provider (AWS, GCP, Azure, etc)
    and manage there credentials.
  platforms:
  # MacOs
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/mateimicu/kdiscover/releases/download/{{ .TagName }}/kdiscover_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-discover
    files:
    - from: "kdiscover"
      to: "kubectl-discover"
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/mateimicu/kdiscover/releases/download/{{ .TagName }}/kdiscover_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-discover
    files:
    - from: "kdiscover"
      to: "kubectl-discover"
    - from: "LICENSE"
      to: "."
  # Linux
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/mateimicu/kdiscover/releases/download/{{ .TagName }}/kdiscover_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-discover
    files:
    - from: "kdiscover"
      to: "kubectl-discover"
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/mateimicu/kdiscover/releases/download/{{ .TagName }}/kdiscover_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-discover
    files:
    - from: "kdiscover"
      to: "kubectl-discover"
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: linux
        arch: 386
    {{addURIAndSha "https://github.com/mateimicu/kdiscover/releases/download/{{ .TagName }}/kdiscover_{{ .TagName }}_linux_386.tar.gz" .TagName }}
    bin: kubectl-discover
    files:
    - from: "kdiscover"
      to: "kubectl-discover"
    - from: "LICENSE"
      to: "."
  # Windows
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/mateimicu/kdiscover/releases/download/{{ .TagName }}/kdiscover_{{ .TagName }}_windows_amd64.zip" .TagName }}
    bin: kubectl-discover.exe
    files:
    - from: "kdiscover.exe"
      to: "kubectl-discover.exe"
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/mateimicu/kdiscover/releases/download/{{ .TagName }}/kdiscover_{{ .TagName }}_windows_arm64.zip" .TagName }}
    bin: kubectl-discover.exe
    files:
    - from: "kdiscover.exe"
      to: "kubectl-discover.exe"
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: windows
        arch: 386
    {{addURIAndSha "https://github.com/mateimicu/kdiscover/releases/download/{{ .TagName }}/kdiscover_{{ .TagName }}_windows_386.zip" .TagName }}
    bin: kubectl-discover.exe
    files:
    - from: "kdiscover.exe"
      to: "kubectl-discover.exe"
    - from: "LICENSE"
      to: "."
